<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

	@foreach ($jobs as $job)
    <url>
		<loc>{{url('/vagas/'. $job['slug'])}}</loc>
		<lastmod>{{ date_format(new DateTime($job['updated_at']), DATE_ATOM) }}</lastmod>
		<image:image>
			<image:loc>{{asset('storage/' . $job['photo'])}}</image:loc>
		</image:image>
	</url>
    @endforeach

	@foreach ($posts as $post)
    <url>
		<loc>{{url('/'. $post['slug'])}}</loc>
		<lastmod>{{ date_format(new DateTime($post['updated_at']), DATE_ATOM) }}</lastmod>
		<image:image>
			<image:loc>{{asset('storage/' . $post['photo'])}}</image:loc>
		</image:image>
	</url>
    @endforeach
</urlset>
<!-- XML Sitemap generated by Edivaldo Jorge -->
